### ISSUE TITLE
`cake bake` may not like some of the output coming from the docker api

### ISSUE THREAD

**Issue by chuckbutler** [bcsaller/layercake#2]
When baking with docker for mac, i'm getting a consistent JSONDecoderError

```
(.venv) charles@Tennoki ~/projects/work/disco $ cake bake -d Dockerfile.1
> /Users/charles/projects/work/disco/.venv/lib/python3.5/site-packages/layer_cake/cake.py(251)bake_main()
-> line = json.loads(line.decode("utf-8"))
(Pdb) line
b'{"stream":"Step 1 : FROM ubuntu\\n"}\r\n'
(Pdb) c
2016-07-22:15:52:30: cake cake.bake_main:251: Step 1 : FROM ubuntu
> /Users/charles/projects/work/disco/.venv/lib/python3.5/site-packages/layer_cake/cake.py(250)bake_main()
-> import pdb; pdb.set_trace()
(Pdb) line
b'{"stream":" ---\\u003e ac526a356ca4\\n"}\r\n{"stream":"Step 2 : MAINTAINER none\\n"}\r\n'
(Pdb) c
Traceback (most recent call last):
  File "/Users/charles/projects/work/disco/.venv/bin/cake", line 11, in <module>
    sys.exit(main())
  File "/Users/charles/projects/work/disco/.venv/lib/python3.5/site-packages/layer_cake/cake.py", line 304, in main
    options.func(options)
  File "/Users/charles/projects/work/disco/.venv/lib/python3.5/site-packages/layer_cake/cake.py", line 250, in bake_main
    import pdb; pdb.set_trace()
  File "/usr/local/Cellar/python3/3.5.2/Frameworks/Python.framework/Versions/3.5/lib/python3.5/json/__init__.py", line 319, in loads
    return _default_decoder.decode(s)
  File "/usr/local/Cellar/python3/3.5.2/Frameworks/Python.framework/Versions/3.5/lib/python3.5/json/decoder.py", line 342, in decode
    raise JSONDecodeError("Extra data", s, end)
json.decoder.JSONDecodeError: Extra data: line 2 column 1 (char 40)
```

The offending line of JSON is:
```
b'{"stream":" ---\\u003e ac526a356ca4\\n"}\r\n{"stream":"Step 2 : MAINTAINER none\\n"}\r\n'
```

**Comment by bcsaller** [comment]
This appears to be a bug in the docker client bindings at first glance. It seems that when in "decode" mode of parsing a response it isn't properly handling universal newlines. I'll attempt to confirm this and/or develop a workaround. 

In the meantime the use of bake is basically syntatic sugar. Installing disco and adding the cake layer <foo> lines to a dockerfile should work.

**Comment by chuckbutler** [comment]
Thats where I left off, was going in manually with what the cake bake was injecting.  I'll give that a go and circle back.
